sudo: required
services:
  - docker

before_install:
  - docker build -t izardasa/docker-react .

script:
  - docker run -e CI=true izardasa/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-485646662895"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

